### PR TITLE
More tags

### LINKED ISSUE #1: Only deploy images on master

### PR DESCRIPTION
**Pull request by hawkrives**
- Deploys extra tags, as requested (such as the light/alpine/begins variants for each minor version, e.g. 5.2-light-alpine)
- Only deploys tags when building on master (closes #1)
- Cleans up the build scripts a good bit
- Disables branch-without-PR builds in Travis
- Updates the README
- Builds the ngnix images from the other named ones, for better accountability

### CODE REVIEW

**Comment by hawkrives** [comment]
I've also disabled branch-without-PR builds in Travis.

**Comment by hawkrives** [comment]
The only-push-tags-on-master bit isn't working properly yet.

**Review by rye — APPROVED** [review]

**Comment by hawkrives** [comment]
More to come

**Review by rye — APPROVED** [review]

**Comment by hawkrives** [comment]
@rye This is now completed.

**Comment by rye** [comment]
Great! Merging.

**Pull request merged**
